project:
  type: website
  output-dir: docs

website:
  title: "HES-portfolio"
  navbar:
    right:
      - icon: github
        href: https://github.com/anouillz/HES-portfolio # link to repo
        aria-label: GitHub

  repo-url: https://github.com/anouillz/HES-portfolio
  repo-actions: [issue]

format:
  html:
    # light / dark theme
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true



